app/auth.py
"""Routes for user authentication."""
from flask import Blueprint, flash, redirect, render_template, request, url_for
from werkzeug.security import generate_password_hash, check_password_hash
import datetime
from flask_login import current_user, login_user, login_required, logout_user

from app.models import User
from app.db import db

# Blueprint Configuration
auth = Blueprint(
    "auth", __name__, template_folder="templates", static_folder="static"
)


@auth.route("/signup")
def signup():
    return render_template('signup.html')


@auth.route('/signup', methods=['POST'])
def signup_post():
    email = request.form.get('email')
    name = request.form.get('name')
    password = request.form.get('password')

    print(email)
    print(name)
    print(password)

    user = User.User.query.filter_by(
        email=email).first()  # if this returns a user, then the email already exists in database

    if user:  # if a user is found, we want to redirect back to signup page so user can try again
        flash('Email address already exists')
        return redirect(url_for('auth.signup'))

    # ct stores current time
    ct = datetime.datetime.now()

    # create a new user with the form data. Hash the password so the plaintext version isn't saved.
    new_user = User.User(email=email, name=name, password=generate_password_hash(password, method='sha256'),
                         created_on=ct, last_login=None)


    # add the new user to the database
    db.session.add(new_user)
    db.session.commit()

    return redirect(url_for('auth.login'))


@auth.route("/login")
def login():
    return render_template('login.html')


@auth.route("/login", methods=["POST"])
def login_post():
    email = request.form.get('email')
    password = request.form.get('password')
    remember = True if request.form.get('remember') else False

    user = User.User.query.filter_by(email=email).first()

    # check if the user actually exists
    # take the user-supplied password, hash it, and compare it to the hashed password in the database
    if not user or not check_password_hash(user.password, password):
        flash('Please check your login details and try again.')
        return redirect(url_for('auth.login'))  # if the user doesn't exist or password is wrong, reload the page

    # ct stores current time
    ct = datetime.datetime.now()

    user.last_login = ct

    db.session.commit()

    # if the above check passes, then we know the user has the right credentials
    login_user(user, remember=remember)
    return redirect(url_for('main.profile'))


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.index'))

app/main.py
from flask import Blueprint, render_template, request
from flask_login import login_required, current_user
import xgboost as XGB
from app.models import User, Estimation
import datetime
import pickle
import pandas as pd

from app.db import db
from app.forms import PredictForm

main = Blueprint('main', __name__)


@main.route('/')
def index():
    form = PredictForm()
    return render_template('index.html', form=form, current_user=current_user)


@main.route('/predict', methods=['POST', 'GET'])
def predict():
    model = load_model()
    rm = float(request.form['rm'])
    lstat = float(request.form['lstat'])
    ptratio = float(request.form['ptratio'])

    d = {'RM': [rm], 'LSTAT': [lstat], 'PTRATIO': [ptratio]}
    res = pd.DataFrame(data=d)

    prediction = model.predict(res)

    formate_pred = "{:.2f}".format(prediction[0])

    if current_user.is_authenticated:
        new_estimation_with_user = Estimation.Estimation(user_id=current_user.id, estimation=prediction[0], rm=rm, lstat=lstat, ptratio=ptratio)
        db.session.add(new_estimation_with_user)
        db.session.commit()

    return render_template('predict.html', prediction=formate_pred)


@main.route('/profile')
@login_required
def profile():

    user_estimations = db.session.query(Estimation.Estimation).filter(
        Estimation.Estimation.user_id == current_user.id).all()

    if not user_estimations:
        form = PredictForm()
        return render_template('index.html', form=form, current_user=current_user)
    else:
        return render_template('profile.html', name=current_user.name, user_estimations=user_estimations)


def load_model():
    # Load the saved model
    with open('app/model/model_boston_housing_v2.pkl', 'rb') as file:
        model = pickle.load(file)

    return model

app/templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Boston Housing</title>

    <link rel="stylesheet" href="https://unpkg.com/spectre.css/dist/spectre.min.css">
    <link rel="stylesheet" href="https://unpkg.com/spectre.css/dist/spectre-exp.min.css">
    <link rel="stylesheet" href="https://unpkg.com/spectre.css/dist/spectre-icons.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="../static/css/style.css">

</head>

<body>
    <section class="hero is-primary is-fullheight">

        <div class="hero-head">
            <nav class="navbar">
                <div class="container">

                    <div id="navbarMenuHeroA" class="navbar-menu">
                        <div class="navbar-end">
                            <a href="{{ url_for('main.index') }}" class="navbar-item">
                                Home
                            </a>
                            {% if current_user.is_authenticated %}
                            <a href="{{ url_for('main.profile') }}" class="navbar-item">
                                Profile
                            </a>
                            {% endif %}
                            {% if not current_user.is_authenticated %}
                            <a href="{{ url_for('auth.login') }}" class="navbar-item">
                                Login
                            </a>
                            <a href="{{ url_for('auth.signup') }}" class="navbar-item">
                                Sign Up
                            </a>
                            {% endif %}
                            {% if current_user.is_authenticated %}
                            <a href="{{ url_for('auth.logout') }}" class="navbar-item">
                                Logout
                            </a>
                            {% endif %}
                            {% if current_user.is_authenticated %}
                            <div class="dropdown">
                                <button class="btn btn-secondary dropdown-toggle"
                                        type="button"
                                        id="dropdownMenuButton"
                                        data-toggle="dropdown"
                                        aria-haspopup="true" aria-expanded="false"
                                        style="background-color: inherit; font-size: 17px;"
                                >
                                    <svg style="position: relative; top: 2px;" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person" viewBox="0 0 16 16">
                                        <path d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z"/>
                                    </svg>
                                    {{ current_user.name }}
                                <span class="caret"></span></button>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                    <a class="dropdown-item" href="#"> Email : {{ current_user.email }}</a>
                                    <a class="dropdown-item" href="#">Last Login : {{ current_user.last_login }}</a>
                                </div>
                            </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </nav>
        </div>

        <div class="hero-body">
            <div class="container has-text-centered">
               {% block content %}
               {% endblock %}
            </div>
        </div>
    </section>
</body>

</html>

app/templates/index.html
{% extends "base.html" %}

{% block content %}
    <div class="sky">
        <div class="title">
            <div class="form-wrapper">
                <form action="{{ url_for('main.predict') }}" method="post">
                    <div class="form-group">
                            {{ form.rm.label(class = "form-label") }}
                            {{ form.rm(class = "form-input") }}

                            {{ form.lstat.label(class = "form-label") }}
                            {{ form.lstat(class = "form-input") }}

                            {{ form.ptratio.label(class = "form-label") }}
                            {{ form.ptratio(class = "form-input") }}

                            {% for error in form.rm.errors %}
                                {{ error }}
                            {% endfor %}
                        {{ form.submit(class = "btn btn-primary") }}
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/login.html
{% extends "base.html" %}

{% block content %}
<div class="column is-4 is-offset-4">
    <h3 class="title">Login</h3>
    <div class="box">
        {% with messages = get_flashed_messages() %}
            {% if messages %}
                <div class="notification is-danger">
                    {{ messages[0] }}
                </div>
            {% endif %}
        {% endwith %}
        <form method="POST" action="/login">
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="email" name="email" placeholder="Your Email" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="password" name="password" placeholder="Your Password">
                </div>
            </div>
            <div class="field">
                <label class="checkbox">
                    <input type="checkbox">
                    Remember me
                </label>
            </div>
            <button class="button is-block is-info is-large is-fullwidth">Login</button>
        </form>
    </div>
</div>
{% endblock %}

app/templates/predict.html
{% extends "base.html" %}

{% block content %}
    <div class="sky">
        <div class="title_predict">

            <section class="container">
                <h1>
                    Le montant prédit est de {{ prediction }} $
                </h1>
            </section>
        </div>
        <div>
            <a href="/" style="position: relative; top: 35px;padding: 8px 15px; border-radius: 20px; text-decoration: none; background-color:#EB984E ; color: #ffffff;">Recommencer</a>
        </div>
    </div>
{% endblock %}

app/templates/profile.html
{% extends "base.html" %}

{% block content %}
<h1 class="title_profile">
    Bonjour {{name}}!
</h1>

<div class="container profile">
    <div class="row">
        <div class="tab_head">
            <div class="col-12 col-md-2"><h3>RM</h3></div>
            <div class="col-12 col-md-2"><h3>LSTAT</h3></div>
            <div class="col-12 col-md-2"><h3>PTRATIO</h3></div>
            <div class="col-12 col-md-3"><h3>ESTIMATION</h3></div>
            <div class="col-12 col-md-3"><h3>DATE</h3></div>
        </div>
    </div>
    <div class="tab">
        {% for user_estimation in user_estimations %}
            <div class="row" style="border-bottom: solid 1px black;">
                <div class="col-12 col-md-2" >
                    {{ user_estimation.rm }}
                </div>
                <div class="col-12 col-md-2" >
                    {{ user_estimation.lstat }}
                </div>
                <div class="col-12 col-md-2" >
                    {{ user_estimation.ptratio }}
                </div>
                <div class="col-12 col-md-3" >
                    {% set estim = user_estimation.estimation | float %}
                    {{ "$%.2f"|format(estim) }} $
                </div>
                <div class="col-12 col-md-3" >
                    {{ user_estimation.created_at }} $
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

app/templates/signup.html
{% extends "base.html" %}

{% block content %}
<div class="column is-4 is-offset-4">
    <h3 class="title">Sign Up</h3>
    <div class="box">

        {% with messages = get_flashed_messages() %}
            {% if messages %}
                <div class="notification is-danger">
                    {{ messages[0] }}. Go to <a href="{{ url_for('auth.login') }}">login page</a>.
                </div>
            {% endif %}
        {% endwith %}
        <form method="POST" action="/signup">
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="email" name="email" placeholder="Email" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="text" name="name" placeholder="Name" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="password" name="password" placeholder="Password">
                </div>
            </div>

            <button class="button is-block is-info is-large is-fullwidth">Sign Up</button>
        </form>
    </div>
</div>
{% endblock %}